#!/bin/sh

# set up generic environment variables
PROXY_BASE_PATH=$(pwd)
PROXY_DEPS_PATH="$PROXY_BASE_PATH/deps"
PROXY_SOURCE_PATH="$PROXY_BASE_PATH/src"
PROXY_CONF_PATH="$PROXY_BASE_PATH/conf"

# set up openresty related environment variables
PROXY_OPENRESTY_VERSION="1.15.8.1"
PROXY_OPENRESTY_TAR_GZ_PATH="$PROXY_DEPS_PATH/openresty-$PROXY_OPENRESTY_VERSION.tar.gz"
PROXY_OPENRESTY_SOURCE_PATH="$PROXY_DEPS_PATH/openresty-$PROXY_OPENRESTY_VERSION"

if [ -z "$PROXY_OPENRESTY_INSTALL_PATH" ]; then
    PROXY_OPENRESTY_INSTALL_PATH="$PROXY_BASE_PATH/build"
fi

# set up openssl related environment variables
PROXY_OPENSSL_VERSION="1.1.1c"
PROXY_OPENSSL_TAR_GZ_PATH="$PROXY_DEPS_PATH/openssl-$PROXY_OPENSSL_VERSION.tar.gz"
PROXY_OPENSSL_SOURCE_PATH="$PROXY_DEPS_PATH/openssl-$PROXY_OPENSSL_VERSION"

# set up docker image build variables
if [ -z "$PROXY_DOCKER_USER" ]; then
    PROXY_DOCKER_USER="oasislabs"
fi

export PROXY_BASE_PATH
export PROXY_DEPS_PATH
export PROXY_CONF_PATH
export PROXY_SOURCE_PATH
export PROXY_OPENRESTY_VERSION
export PROXY_OPENRESTY_TAR_GZ_PATH
export PROXY_OPENRESTY_SOURCE_PATH
export PROXY_OPENRESTY_INSTALL_PATH
export PROXY_OPENSSL_VERSION
export PROXY_OPENSSL_TAR_GZ_PATH
export PROXY_OPENSSL_SOURCE_PATH
export PROXY_DOCKER_USER

